#!/usr/bin/env python
from innok_heros_driver.can_bms import CANBmsPublisher 
import rclpy

if __name__ == '__main__':
    rclpy.init()
    can_bms_publisher = CANBmsPublisher()
    can_bms_publisher.run()

