#!/usr/bin/env python

from innok_heros_driver.heros_diagnostics import HerosDiagnostics
import rclpy 

if __name__ == '__main__':
    rclpy.init()
    diagnosticNode = HerosDiagnostics()  
    diagnosticNode.run()
